#!/bin/sh

echo "install toolchain"
rustup default stable
rustup target install wasm32-unknown-unknown

echo "install bindgen"
cargo install wasm-bindgen-cli

echo "building"
cargo build --release --target wasm32-unknown-unknown $@

echo "generating bindings"
wasm-bindgen --out-dir ./web/scripts --target web ./target/wasm32-unknown-unknown/release/bordtennis.wasm

echo "cp assets"
cp assets web/assets -r
