#!/bin/sh

echo "install toolchain"
rustup target install wasm32-unknown-unknown
rustup default stable

echo "install bindgen"
cargo install wasm-bindgen-cli

echo "run bindgen"
wasm-bindgen --out-dir ./web/scripts --target web ./target/wasm32-unknown-unknown/release/bordtennis.wasm

echo "cp assets"
cp assets web/assets -r
